# Generated by Django 4.2.6 on 2023-11-21 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='patronumic',
            new_name='patronymic',
        ),
    ]
